### PR TITLE
Add iOS framework support

### PR DESCRIPTION
**Pull request by parrotbait**
Firstly, thank you very much for this library. I was looking for exactly this library for iOS.
I have added an iOS framework target by doing the following:
* Convert NSAlerts to fatalErrors. I think crashing is nicer than displaying an error in a host app, a hard crash here tells the developer immediately that something is wrong.
* Added a compile-time switch to the tests so they work on both iOS and OSX.

The rest is all just boilerplate iOS project stuff. 

All tests work on both platforms.

I have this linked in an iOS app and it works fine although I am using just the IBAN validation part of the library.

### CODE REVIEW

**Review by mike-lischke — CHANGES_REQUESTED** [review]
Thanks for your contribution! However, I don't agree with your change of the error messages to fatal errors. Imagine use cases were the lib is used as part of a larger app (say, a banking app), for which missing IBAN functionality is not fatal, since you can still do other stuff. Crashing the entire app because of a missing file will only cause frustration for the user. So please convert the fatal errors back to messages.

**Comment by parrotbait** [comment]
I did this to remove the AppKit requirement due to NSAlert being used. I can maybe have a similar switch as the tests to use a UIAlertViewController on iOS.

However taking that use case as an example having a dialog is also not a good solution because the banking app in question may want to fail silently in that case and not display a modal dialog to the end user which will mean nothing to them. Also on iOS you need to provide text for dialogs and definitely don't want to get into localization etc. of the popups :)
I could log a warning for iOS and use a popup on OSX to retain previous behaviour.

 So yes I agree that perhaps crashing is not the best idea if the files are optional to include (I didn't realise this). An ideal solution here would be to have an error code returned to the user if they attempt to use functionality that requires a given file. That said, that would also require a re-write of the public API to deal with this and add complexity. 

Interested to hear your thoughts on it.

**Comment by mike-lischke** [comment]
You brought up valid points indeed. I think I used a completely wrong approach there anyway. A library shouldn't show a message box. That's up to the application (GUI) layer, which then can also take care for logging the error, localization and proper handling (app shutdown, disable specific features, etc.).

Instead that method `loadData` should not catch errors at all and let any error bubble up, to allow the application to handle them. Can you please remove the do/catch block around the loader code?

**Comment by parrotbait** [comment]
Apologies for the delay, $life got in the way...

Agree with your comments and the host app should perform any error handling themselves.

Anyhow I've made those changes along with a TODO there to remind for the future. 

Thanks again for the library!

**Review by mike-lischke — APPROVED** [review]

**Pull request merged**
